#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/watchgit" ]; then
	update-rc.d watchgit defaults >/dev/null
	invoke-rc.d watchgit start || exit $?
fi
# End automatically added section
